namespace WFDotnet.Code.Common.Constants
{
	public class GeneratedCodeDefaultNamespace
	{
		public const string DefaultNamespace = "WFDotnet.AutoGenerated";

		public static string GetDefaultNamespace(string moduleName)
		{
			return $"{DefaultNamespace}.{moduleName}";
		}

	}
}

